openapi: 3.0.3
info:
  title: LMS - API 1.0.0
  description: |-
    This is a sample Library Management System based on the LMS API 1.0.0
  version: 1.0.11
servers:
  - url: http://localhost:8080

# BOOKS API'S
tags:
  - name: Books
    description: ALL BOOKS API
  - name: Users
    description: Members API
paths:
  /books:
    get:
      tags:
        - Books
      summary: Returns all books.
      description: A list of all books that present in the library
      responses:
        "200":
          description: Success Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/books"

  /books/all/{bookId}:
    get:
      tags:
        - Books
      summary: Returns Requested Single Book
      description: Find The Requested Book By Bookid
      parameters:
        - in: path
          name: bookId
          description: any text results found,then return results
          required: true
          schema:
            type: number
      responses:
        "200":
          description: Success RESPONSE
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/books"
        "404":
          description: PAGE NOT FOUND
        "500":
          description: INTERNAL SERVER ERROR

  /books/search:
    get:
      tags:
        - Books
      summary: Returns All Search Results Books
      description: Find The Requested Books By Any Text
      parameters:
        - name: q
          in: query
          description: any text results found,then return results
          required: true
          schema:
          type: string
      responses:
        "200":
          description: Success RESPONSE
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/books"
        "404":
          description: PAGE NOT FOUND
        "500":
          description: INTERNAL SERVER ERROR

  /books/admin/create:
    post:
      tags:
        - Books
      summary: Add New Book To The Library
      description: A Successl request will add new book to the library
      parameters:
        - in: body
          name: user
          description: New Book Will Be Added
          schema:
            type: object
            required:
              - bookId
              - name
              - author
              - category
              - quantity
              - rating
              - published_date
              - pages
              - availabilty
          properties:
            bookId:
              type: integer
            name:
              type: string
            author:
              type: number
            category:
              type: string
            quantity:
              type: string
            rating:
              type: number
            published_date:
              type: date
            pages:
              type: string
            availabilty:
              type: boolean
      responses:
        "200":
          description: Success RESPONSE
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/books"
        "404":
          description: PAGE NOT FOUND
        "500":
          description: INTERNAL SERVER ERROR

  /books/admin/update/{bookId}:
    put:
      tags:
        - Books
      summary: Update Book In The Library
      description: A Successl request will update new book to the library
      parameters:
        - in: path
          name: bookId
        - in: body
          name: user
          description: The user to create.
          schema:
            type: object
          properties:
            bookId:
              type: integer
            name:
              type: string
            author:
              type: number
            category:
              type: string
            quantity:
              type: string
            rating:
              type: number
            published_date:
              type: date
            pages:
              type: string
            availabilty:
              type: boolean
      responses:
        "200":
          description: Success RESPONSE
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/books"
        "404":
          description: PAGE NOT FOUND
        "500":
          description: INTERNAL SERVER ERROR

  /books/purchase/book:
    post:
      tags:
        - Books
      summary: Purchase A Book From The Library
      description: User Will Purchase A Book
      parameters:
        - in: body
          name: user
          description: Purchasing A Book
          schema:
            type: object
            required:
              - bookId
              - userId
          properties:
            book_id:
              type: integer
            user_id:
              type: integer
      responses:
        "200":
          description: Success RESPONSE
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/books"
        "404":
          description: PAGE NOT FOUND
        "500":
          description: INTERNAL SERVER ERROR

  /user/register:
    post:
      tags:
        - USERS
      summary: Registering The User In The DataBase
      description: User Will Be Registered In Library,After Successl Request
      parameters:
        - in: body
          name: user
          description: Registration
          schema:
            type: object
            required:
              - username
              - password
              - role
              - joining_date
          properties:
            username:
              type: string
            password:
              type: string
            role:
              type: string
            joining_date:
              type: date

      responses:
        "200":
          description: Success RESPONSE
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/books"
        "404":
          description: PAGE NOT FOUND
        "500":
          description: INTERNAL SERVER ERROR

  /user/login:
    post:
      tags:
        - USERS
      summary: User Login
      description: User Will Be Get Access To Library,After Success Request
      parameters:
        - in: body
          name: user
          description: User Login
          schema:
            type: object
            required:
              - username
              - password
          properties:
            username:
              type: string
            password:
              type: string

      responses:
        "200":
          description: Success RESPONSE
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/books"
        "404":
          description: PAGE NOT FOUND
        "500":
          description: INTERNAL SERVER ERROR

components:
  schemas:
    books:
      type: object
      properties:
        book_id:
          type: string
        title:
          type: string
        author:
          type: string
        category:
          type: string
        availablity:
          type: boolean
        publish_year:
          type: integer
        rating:
          type: integer
        lib_book_id:
          type: string
        language:
          type: string
        pages:
          type: integer
        cover:
          type: string
        created_at:
          type: Date
        updated_at:
          type: Date

      example:
        book_id: 8cc005d6-0ccd-485c-97e8-f212c16f876d
        title: last game
        author: rakshat
        category: novel
        availablity: false
        publish_year: 1998,
        rating: 8
        lib_book_id: 2b6076
        language: english
        pages: 130
        cover: https://m.media-amazon.com/images/I/51L57joruVL.jpg
        created_at: 2022-12-07T16:08:09.755Z
        updated_at: 2022-12-07T16:08:09.755Z

    users:
      type: object
      required:
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: string
        joining_date:
          type: date

      example:
        username: "Hritik"
        password: "Roshan"
        role: "user"
        joining_date: "2021-02-22"
